### ISSUE TITLE
Unpredictable behavior around `during` and `atMost` of Awaitility

### ISSUE THREAD

**Issue by uraniumdawn** [awaitility/awaitility#180] opened 2020-07-12 18:01 UTC
While I was testing Kafka I end up with some issues around Awaitility. The goal was to test that Kafka topic doesn't contain the new records for a specified time. This is the simplified scratch of my test but it shows the problem. I expect that ConditionTimeoutException doesn't throw in this case. But it does.
```
public static void main(String[] args) {
        List<String> list = new ArrayList<>();
        await("wait").during(5_000, TimeUnit.MILLISECONDS).atMost(5_000, TimeUnit.MILLISECONDS)
                .pollInterval(100, TimeUnit.MILLISECONDS)
                .until(() -> list, List::isEmpty);
}
```
I increased the atMost timeout to 5000 + pollInterval -> 5100 but still end up with an exception. On my local machine throwing exception was stoped closed the value of atMost timeout of 5170-5180. Should I keep something in mind? Or may the test isn't correct?

**Comment by grofoli** [comment] 2020-07-13 16:49
@johanhaleby I have seen this issue is under discussion also in Google Groups. I was wondering if I can help you with this - it is a long time since my last contribution :-) - but I would like to ask for a little guidance here if possible. So for example a branch with some failing tests that describe the expected behaviour and that I can make "green" with my contribution. Would this be a good approach/a help for you?

**Comment by johanhaleby** [comment] 2020-07-15 15:52
@grofoli Thanks a lot for wanting to help :) 

@uraniumdawn Could you perhaps provide a test case that shows the failing behavior?

**Comment by uraniumdawn** [comment] 2020-07-16 07:28
@johanhaleby Code snippet mentioned in ahead of this topic actually fails. And could be used as a test case suppose.

**Comment by grofoli** [comment] 2020-07-16 08:00
@johanhaleby @uraniumdawn I would really appreciate 2-3 unit tests that describe the expected behavior. Maybe I miss something here, does it really makes sense to use `during` and `atMost` with the same or almost the same values?

**Comment by uraniumdawn** [comment] 2020-07-16 09:20
As I said previously, I had to be sure that Kafka's topic doesn't receive new messages for a specific time. That is why I used `during` and `atMost`. To provide the exact time. No more, no less. I would appreciate getting another solution. As for the unit tests, I'll do ones.

**Comment by 0xERR0R** [comment] 2020-08-26 12:30
If you use  `during` together with `atMost`, the `atMost` time must be greater (await needs some time to evaluate the condition). This code works
```java
  public static void main(String[] args) {
    List<String> list = new ArrayList<>();
    await("wait").during(5_000, TimeUnit.MILLISECONDS).atMost(5_500, TimeUnit.MILLISECONDS)
            .pollInterval(100, TimeUnit.MILLISECONDS)
            .until(() -> list, List::isEmpty);
  }
```

**Comment by uraniumdawn** [comment] 2020-09-08 06:12
@johanhaleby @grofoli You are right Oliver. It no makes sense to have a `during` and `atMost` at the same time. The first one covers my requirement. Sorry for wasting your time.

**Comment by johanhaleby** [comment] 2020-09-13 13:28
@uraniumdawn Should we close this issue?

**Comment by uraniumdawn** [comment] 2020-09-13 17:55
@johanhaleby Yes

**Closed** 2020-09-21 07:19 UTC
