### ISSUE TITLE
condition only evaluated for first wait when using custom pollThread

### ISSUE THREAD

**Issue by rbrindl** [awaitility/awaitility#101] opened 2018-01-15 11:27 UTC
See unit test below.

The first `await` is always successful, as expected. 
The second `await` is also always successful, although I would expect it to fail, since the condition always returns false. Also, the output of the second condition is never printed, the condition is not evaluated at all.
If I debug into `ConditionAwaiter.await` I see that the executor is in shutdown state, and the evaluation loop is never entered. 

The problem seems to be that `Awaitility#defaultPollExecutorService` is a static field that is set only once when `pollThread` is called. All wait instances use the same Executor thereafter.

The actual reason why I wanted to use pollThread was because I would like to customize thread names.

```
import org.awaitility.Awaitility;
import org.junit.Test;

public class AwaitilityCustomThreadMultipleWaitTest {
	@Test
	public void test() {
		Awaitility.pollThread(runnable -> new Thread(Thread.currentThread().getThreadGroup(), runnable, "mythread"));
		Awaitility.await("first").until(() -> {
			System.out.println("first");
			return true;
		});
		Awaitility.await("second").until(() -> {
			System.out.println("second");
			return false;
		});
	}
}
```

**Comment by johanhaleby** [comment] 2018-03-02 10:55
Sorry for the late response. I've reproduced this. The reason for the bug is that Awaitility shuts down the executor service (generated implicitly) after each condition evaluation round (each call to the `until` method). My suggestion on how to solve this is:

If you supply a custom executor or thread YOU as the Awaitility user is responsible for handling cleanup. The change would thus imply that:

```
Awaitility.pollThread(runnable -> new Thread(Thread.currentThread().getThreadGroup(), runnable, "mythread"));
```

retains the generated thread for all condition evaluations and all tests. This was actually not the intention, the intention was that a new thread was created for each condition evaluation round (each call to `until`) but this obviously wasn't tested enough and didn't work.

WDYT?

Another example would be if one did this:

```
Awaitility.pollExecutorService(Executors.newSingleThreadExecutor());
```

Here it feels very strange (and inaccurate) to shutdown this executor service after each condition evaluation (as is done today). I suppose that the intention of the user is to use this executor service for ALL condition evaluations in all tests?

**Comment by johanhaleby** [comment] 2018-03-02 11:24
Question, what do you think should happen in this case when static configuration is not used:

```java
Function<Runnable, Thread> threadFn = runnable -> {
    Thread thread = new Thread(Thread.currentThread().getThreadGroup(), runnable, "mythread");
    return thread;
};

with().pollThread(threadFn).await("first").until(() -> {
	return true;
});

with().pollThread(threadFn).await("second").until(() -> {
    return true;
});
```

Is the thread created once and the same thread is used in both first and second? Or is the thread created only once and shared between first and second?

**Comment by johanhaleby** [comment] 2018-03-02 11:35
This is tricky... Perhaps this is how it should work:

1. If poll thread is defined by a *function*, regardless of whether it's defined statically (`Awaitility.setPollThread(runnable -> ...)`) or as an instance (`with().pollThread(threadFn).await(..)`) we should generate a new thread for each call to `until`?
1. If poll thread is defined using a Thread *instance* we cannot generate a new instance for each call to `until` nor can we shut it down automatically afterwards. This is the responsibility of the user.
1. The same logic can be applied when defining ExecutorServices and functions creating executor services. 

There's one problem I see with this and that is if you define your poll thread function like this:

```java
Thread thread = new Thread(Thread.currentThread().getThreadGroup(), runnable, "mythread");
Function<Runnable, Thread> threadFn = runnable -> thread;
```

I.e. you return the same thread *instance* in the function. With the behavior explained above the thread pool will be shutdown..

**Comment by johanhaleby** [comment] 2018-03-02 12:45
I think I've fixed this now, at least now it works as intended , so closing issue.

**Closed by johanhaleby** 2018-03-02 12:45 UTC
